services:
  neo4j:
    image: neo4j:KGV2
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/sebastienM19
        - NEO4JLABS_PLUGINS= '["n10s"]'         
        - NEO4J_dbms_security_procedures_unrestricted= "n10s.*"
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
volumes:
  neo4j_data:
  neo4j_logs: