# docker-compose.yml
version: "3.9"

services:
  neo4j:
    image: neo4j:5.18
    container_name: neo4j-kg
    restart: unless-stopped

    environment:
      NEO4J_AUTH: "neo4j/sebastienM19"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # install Labs plug-ins
      NEO4JLABS_PLUGINS: '["n10s"]'

      # allow n10s procedures
      NEO4J_dbms_security_procedures_unrestricted: "n10s.*"

      # tell Neo4j that /import is the whitelisted folder
      NEO4J_server_directories_import: "/import"

    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./export:/import            # ← host ./export  ↔  container /import

    ports:
      - "7474:7474"
      - "7687:7687"
